worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server_tokens off;

    limit_req_zone $binary_remote_addr zone=per_ip:10m rate=5r/s;
    limit_conn_zone $binary_remote_addr zone=per_ip_conn:10m;

    include /etc/nginx/conf.d/*.conf;
}
