export {
  FLAT_SCALE,
  SHARP_SCALE,
  LETTER_ORDER,
  NATURAL_PITCH,
  accidentalForOffset,
  degreeClassForNote,
  intervalLabelForDefinition,
  intervalLabelForNote,
  noteNameToPitchClass,
  noteSelectionMatches,
  normalizeKey,
  normalizeNoteName,
  normalizeText,
  shouldUseFlats,
  intervalLabelForScale,
  signatureNotesForAccidentals,
  signatureSelectionMatches,
} from "../app/fretboard/fretboard_note_helpers.js";
